default:
  tags:
    - tkbpay
    - gitrun01

include:
  - component: $CI_SERVER_FQDN/tkbpay/pay/platform/ci-templates/java-spring@1.1.39
    inputs:
      with_cert: true
      image_name: pay-limit-management
      k8s_context: tkbpay/pay/platform/kubernetes-agents:test
