server:
  port: ${SERVER_PORT:8084}

pay:
  environment: ${PAY_ENVIRONMENT:local}

spring:
  application:
    name: pay-limit-management
  profiles:
    default: local
  config:
    import:
      - optional:configserver:${CONFIG_SERVER_URL:http://pay-payconfig-server:8080}
      - optional:vault://
  datasource:
    url: ${PAY_LIMIT_MANAGEMENT_DB_URL:jdbc:postgresql://localhost:5432/pay_admin?currentSchema=limit_management}
    username: ${PAY_LIMIT_MANAGEMENT_DB_USERNAME:pay_admin}
    password: ${PAY_LIMIT_MANAGEMENT_DB_PASSWORD:}
  flyway:
    enabled: ${PAY_LIMIT_MANAGEMENT_FLYWAY_ENABLED:true}
    schemas: limit_management
    default-schema: limit_management
  cloud:
    config:
      enabled: ${CONFIG_SERVER_ENABLED:false}
      label: ${CONFIG_SERVER_LABEL:${pay.environment}}
      username: ${CONFIG_CLIENT_USERNAME:}
      password: ${CONFIG_CLIENT_PASSWORD:}
    vault:
      enabled: ${VAULT_ENABLED:false}
      kv:
        backend: ${VAULT_KV_BACKEND:pay}
        default-context: ""
        application-name: ${VAULT_KV_CONTEXTS:${pay.environment}/${spring.application.name}-db-password}
        profiles: []

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

pay-limit-management:
  service-name: ${PAY_LIMIT_MANAGEMENT_SERVICE_NAME:Limit Management}
  runtime-manifest:
    min-activation-lead-time: ${PAY_LIMIT_MANAGEMENT_RUNTIME_MANIFEST_MIN_ACTIVATION_LEAD_TIME:5m}
